#!/usr/bin/env node
/**
 * Build orchestrator for SecurePass Manager Browser Extension.
 * Supports multi-browser builds with environment-driven manifest adjustments.
 */
import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');

interface BuildResult {
  browser: string;
  success: boolean;
  error?: string;
  outputPath: string;
}

const browsers = ['chrome', 'firefox', 'edge'];

function cleanDist(): void {
  const distDir = path.join(rootDir, 'dist');
  if (fs.existsSync(distDir)) {
    fs.rmSync(distDir, { recursive: true, force: true });
    console.log('Cleaned dist/ directory');
  }
}

function buildForBrowser(browser: string): BuildResult {
  const outputPath = path.join(rootDir, 'dist', browser);

  try {
    console.log(`\n🏗️  Building for ${browser.toUpperCase()}...`);
    execSync(`npx vite build`, {
      cwd: rootDir,
      env: { ...process.env, TARGET_BROWSER: browser, NODE_ENV: 'production' },
      stdio: 'inherit',
    });

    // Validate output
    if (!fs.existsSync(outputPath)) {
      throw new Error(`Build output not found at ${outputPath}`);
    }

    console.log(`✅ Build for ${browser.toUpperCase()} completed at dist/${browser}/`);
    return { browser, success: true, outputPath };
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    console.error(`❌ Build for ${browser.toUpperCase()} failed:`, error);
    return { browser, success: false, error, outputPath };
  }
}

function copyFirefoxManifest(outputPath: string): void {
  const firefoxManifestSrc = path.join(rootDir, 'manifest-v2.json');
  const firefoxManifestDest = path.join(outputPath, 'manifest.json');

  if (fs.existsSync(firefoxManifestSrc)) {
    fs.copyFileSync(firefoxManifestSrc, firefoxManifestDest);
    console.log('📄 Copied Firefox MV2 manifest');
  } else {
    console.warn('⚠️  manifest-v2.json not found; using base manifest with Firefox overrides');
  }
}

function generateSourceMapSources(outputPath: string): void {
  const sourceMapDir = path.join(outputPath, 'source-maps');
  fs.mkdirSync(sourceMapDir, { recursive: true });

  // Source maps are already generated by Vite. Just log for audit.
  const files = fs.readdirSync(outputPath, { recursive: true }) as string[];
  const mapFiles = files.filter((f) => typeof f === 'string' && f.endsWith('.map'));
  console.log(`📍 Source maps generated: ${mapFiles.length} file(s)`);
}

function main(): void {
  const args = process.argv.slice(2);
  const requestedBrowser = args[0];

  if (requestedBrowser && !browsers.includes(requestedBrowser)) {
    console.error(`Unknown browser: ${requestedBrowser}. Expected one of: ${browsers.join(', ')}`);
    process.exit(1);
  }

  const targets = requestedBrowser ? [requestedBrowser] : browsers;

  cleanDist();

  const results: BuildResult[] = targets.map((browser) => {
    const result = buildForBrowser(browser);

    if (result.success) {
      if (browser === 'firefox') {
        copyFirefoxManifest(result.outputPath);
      }
      generateSourceMapSources(result.outputPath);
    }

    return result;
  });

  // Summary
  console.log('\n╔════════════════════════════════════════════════════════════╗');
  console.log('║                    BUILD SUMMARY                           ║');
  console.log('╠════════════════════════════════════════════════════════════╣');
  for (const r of results) {
    const status = r.success ? '✅ PASS' : '❌ FAIL';
    console.log(`║ ${status}  ${r.browser.padEnd(9)} → ${r.outputPath}`);
    if (r.error) {
      console.log(`║          Error: ${r.error}`);
    }
  }
  console.log('╚════════════════════════════════════════════════════════════╝');

  const failed = results.filter((r) => !r.success);
  if (failed.length > 0) {
    console.error(`\n❌ ${failed.length} build(s) failed.`);
    process.exit(1);
  }

  console.log('\n🎉 All builds completed successfully!');
}

main();
