export const IPC_CHANNELS = {
  AUTH_INIT: 'auth:init',
  AUTH_UNLOCK: 'auth:unlock',
  AUTH_LOCK: 'auth:lock',
  AUTH_CHANGE_PASSWORD: 'auth:change-password',
  AUTH_CHECK: 'auth:check',
  AUTH_LOCKED: 'auth:locked',

  VAULT_LIST: 'vault:list',
  VAULT_CREATE: 'vault:create',
  VAULT_SELECT: 'vault:select',
  VAULT_RENAME: 'vault:rename',
  VAULT_DELETE: 'vault:delete',
  VAULT_SET_DEFAULT: 'vault:setDefault',
  VAULT_REVEAL_LOCATION: 'vault:revealLocation',
  VAULT_GET_ACTIVE: 'vault:getActive',
  VAULT_IMPORT_FILE_DIALOG: 'vault:importFileDialog',
  VAULT_IMPORT: 'vault:import',
  VAULT_BACKUP_FILE_DIALOG: 'vault:backupFileDialog',
  VAULT_BACKUP: 'vault:backup',
  VAULT_RESTORE_FILE_DIALOG: 'vault:restoreFileDialog',
  VAULT_RESTORE: 'vault:restore',
  VAULT_RECOVER: 'vault:recover',
  VAULT_CHECK_FILES: 'vault:checkFiles',
  VAULT_REMOVE_MISSING: 'vault:removeMissing',

  FOLDER_GET_TREE: 'folder:getTree',
  FOLDER_CREATE: 'folder:create',
  FOLDER_UPDATE: 'folder:update',
  FOLDER_MOVE: 'folder:move',
  FOLDER_DELETE: 'folder:delete',
  FOLDER_RESTORE: 'folder:restore',

  ITEM_GET_BY_FOLDER: 'item:getByFolder',
  ITEM_GET_BY_ID: 'item:getById',
  ITEM_CREATE: 'item:create',
  ITEM_UPDATE: 'item:update',
  ITEM_DELETE: 'item:delete',
  ITEM_RESTORE: 'item:restore',
  ITEM_TOGGLE_FAVORITE: 'item:toggleFavorite',
  ITEM_SEARCH: 'item:search',
  ITEM_SEARCH_BY_TAG: 'item:searchByTag',
  ITEM_GET_ALL: 'item:getAll',

  OTP_GENERATE: 'otp:generate',
  OTP_GET_CONFIG: 'otp:getConfig',
  OTP_CHECK_TIME_SYNC: 'otp:checkTimeSync',

  HEALTH_ANALYZE: 'health:analyze',

  TAG_GET_ALL: 'tag:getAll',
  TAG_CREATE: 'tag:create',
  TAG_ATTACH: 'tag:attach',
  TAG_DETACH: 'tag:detach',
  TAG_DELETE: 'tag:delete',

  FILE_GET_BY_ITEM: 'file:getByItem',
  FILE_ATTACH: 'file:attach',
  FILE_DOWNLOAD: 'file:download',
  FILE_DELETE: 'file:delete',

  COVER_UPLOAD: 'cover:upload',
  COVER_READ: 'cover:read',
  COVER_DELETE: 'cover:delete',

  POWER_MONITOR_LOCK_SCREEN: 'power-monitor:lock-screen',
  POWER_MONITOR_SUSPEND: 'power-monitor:suspend',

  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_GET_ALL: 'settings:getAll',

  TRASH_GET: 'trash:get',
  TRASH_RESTORE: 'trash:restore',
  TRASH_PERMANENT_DELETE: 'trash:permanentDelete',
  TRASH_EMPTY: 'trash:empty',
  TRASH_PURGE: 'trash:purge',

  IMPORT_OPEN_FILE_DIALOG: 'import:openFileDialog',
  IMPORT_PARSE_FILE: 'import:parseFile',
  IMPORT_GET_CSV_HEADERS: 'import:getCsvHeaders',
  IMPORT_PARSE_GENERIC_CSV: 'import:parseGenericCsv',
  IMPORT_CHECK_DUPLICATES: 'import:checkDuplicates',
  IMPORT_COMMIT: 'import:commit',

  EXPORT_DATA: 'export:data',
  EXPORT_PROGRESS: 'export:progress',

  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSE: 'window:close',
  WINDOW_IS_MAXIMIZED: 'window:isMaximized',

  // Global shortcuts
  SHORTCUT_GET_BINDINGS: 'shortcut:getBindings',
  SHORTCUT_UPDATE_BINDING: 'shortcut:updateBinding',
  SHORTCUT_REGISTER: 'shortcut:register',
  SHORTCUT_UNREGISTER: 'shortcut:unregister',
  SHORTCUT_ACTION: 'shortcut:action',
  SHORTCUT_ENABLED_STATE: 'shortcut:enabledState',

  // Auto-updater
  UPDATE_AVAILABLE: 'update:available',
  UPDATE_NOT_AVAILABLE: 'update:not-available',
  UPDATE_DOWNLOAD_PROGRESS: 'update:download-progress',
  UPDATE_DOWNLOADED: 'update:downloaded',
  UPDATE_ERROR: 'update:error',
  CHECK_FOR_UPDATES: 'update:check',
  DOWNLOAD_UPDATE: 'update:download',
  QUIT_AND_INSTALL: 'update:quit-and-install',

  // Quick Picker
  QUICK_PICKER_SEARCH: 'quickPicker:search',
  QUICK_PICKER_ACTION: 'quickPicker:action',
  QUICK_PICKER_SHOW: 'quickPicker:show',
  QUICK_PICKER_HIDE: 'quickPicker:hide',
  QUICK_PICKER_GET_ITEMS: 'quickPicker:getItems',
  QUICK_PICKER_ITEMS: 'quickPicker:items',
  QUICK_PICKER_FOCUS_SEARCH: 'quickPicker:focusSearch',

  // Clipboard management
  CLIPBOARD_COPY: 'clipboard:copy',
  CLIPBOARD_STATUS: 'clipboard:status',
  CLIPBOARD_ON_STATUS_CHANGE: 'clipboard:onStatusChange',
  CLIPBOARD_CLEAR_STATUS_LISTENER: 'clipboard:clearStatusListener',
} as const;
